# Generated by Django 4.2 on 2023-05-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "About",
                    models.TextField(
                        help_text="About charitable assosiation ", max_length=100000
                    ),
                ),
                (
                    "Image",
                    models.ImageField(
                        default=0, help_text="insert about image ", upload_to=""
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(help_text="Name of cash donation", max_length=100),
                ),
                (
                    "Email",
                    models.EmailField(
                        help_text="Email address of cash donation", max_length=100
                    ),
                ),
                (
                    "PhoneNumber",
                    models.IntegerField(help_text="Phone number of cash donation"),
                ),
                (
                    "Country",
                    models.CharField(
                        help_text="Country of cash donation member", max_length=100
                    ),
                ),
                ("Cash", models.IntegerField(help_text="Cash donation")),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "NameOfEvent",
                    models.CharField(help_text="Name of Event", max_length=100),
                ),
                (
                    "Location",
                    models.CharField(help_text="Location of event", max_length=100),
                ),
                (
                    "DateTimeOFEvent",
                    models.DateTimeField(
                        help_text="Date and time of event", max_length=100
                    ),
                ),
                (
                    "Description",
                    models.TextField(help_text="Description of event", max_length=400),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExistingProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(
                        help_text="project poster image ", max_length=400, upload_to=""
                    ),
                ),
                ("Name", models.CharField(help_text="Name of project", max_length=100)),
                (
                    "Details",
                    models.TextField(help_text="project details ", max_length=500),
                ),
                ("start_date", models.DateField(help_text="project start date")),
            ],
        ),
        migrations.CreateModel(
            name="InKindDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Name",
                    models.CharField(
                        help_text="Name of in kind donation ", max_length=100
                    ),
                ),
                (
                    "Email",
                    models.EmailField(
                        help_text="Email address of in kind donation", max_length=100
                    ),
                ),
                (
                    "PhoneNumber",
                    models.IntegerField(help_text="Phone number of in kind donation"),
                ),
                (
                    "Country",
                    models.CharField(
                        help_text="Country of in kind donation", max_length=100
                    ),
                ),
                (
                    "TypeOfDonation",
                    models.CharField(help_text="Type of donation", max_length=100),
                ),
                (
                    "AmountOfDonation",
                    models.FloatField(help_text="Amount of donation", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(help_text="Title of news", max_length=100)),
                (
                    "Image",
                    models.ImageField(help_text="Image Poster for news ", upload_to=""),
                ),
                ("Details", models.TextField(help_text="News details", max_length=100)),
                ("date", models.DateField(help_text="Date of news")),
            ],
        ),
        migrations.CreateModel(
            name="NumberOfAchivment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Test", models.CharField(blank=True, help_text="00")),
                (
                    "FamilyAidNumber",
                    models.IntegerField(default=0, help_text="Number of family aids "),
                ),
                (
                    "ProjectsGrants",
                    models.IntegerField(
                        default=0, help_text="number of pojects grants"
                    ),
                ),
                (
                    "EducationBeneficiaries",
                    models.IntegerField(
                        default=0, help_text="Number of education beneficiaries "
                    ),
                ),
                (
                    "HomeProjects",
                    models.IntegerField(
                        default=0, help_text="Number of home projects "
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="poster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(help_text="Image Poster for news ", upload_to=""),
                ),
                ("details", models.CharField(help_text="News details", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_of_volunteers",
                    models.CharField(
                        help_text="type or field of voulnteer", max_length=100
                    ),
                ),
                ("RegisterDate", models.DateField(help_text="Date of registration")),
            ],
        ),
    ]
