# Generated by Django 4.2 on 2023-06-03 13:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.TextField(help_text='About charitable assosiation ', max_length=100000)),
                ('Image', models.ImageField(default=0, help_text='insert about image ', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Achivment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Test', models.CharField(blank=True, default=0)),
                ('FamilyAidNumber', models.IntegerField(default=0, help_text='Number of family aids ')),
                ('ProjectsGrants', models.IntegerField(default=0, help_text='number of pojects grants')),
                ('EducationBeneficiaries', models.IntegerField(default=0, help_text='Number of education beneficiaries ')),
                ('HomeProjects', models.IntegerField(default=0, help_text='Number of home projects ')),
            ],
        ),
        migrations.CreateModel(
            name='CashDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name of cash donation', max_length=100)),
                ('Email', models.EmailField(help_text='Email address of cash donation', max_length=100)),
                ('PhoneNumber', models.IntegerField(help_text='Phone number of cash donation')),
                ('Country', models.CharField(help_text='Country of cash donation member', max_length=100)),
                ('Cash', models.IntegerField(help_text='Cash donation')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfEvent', models.CharField(help_text='Name of Event', max_length=100)),
                ('Location', models.CharField(help_text='Location of event', max_length=100)),
                ('DateTimeOFEvent', models.DateTimeField(help_text='Date and time of event', max_length=100)),
                ('Description', models.TextField(help_text='Description of event', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ExistingProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(help_text='project poster image', upload_to='')),
                ('Name', models.CharField(help_text='Name of project', max_length=100)),
                ('Details', models.TextField(help_text='project details ', max_length=500)),
                ('start_date', models.DateField(help_text='project start date')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField(help_text='enter your idea details : ')),
                ('name', models.CharField(help_text='enter your name :', max_length=100)),
                ('PhoneNumber', models.CharField(blank=True, help_text='enter phone number', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 digits', regex='^\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='InKindDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name of in kind donation ', max_length=100)),
                ('Email', models.EmailField(help_text='Email address of in kind donation', max_length=100)),
                ('PhoneNumber', models.IntegerField(help_text='Phone number of in kind donation')),
                ('Country', models.CharField(help_text='Country of in kind donation', max_length=100)),
                ('TypeOfDonation', models.CharField(help_text='Type of donation', max_length=100)),
                ('AmountOfDonation', models.FloatField(help_text='Amount of donation', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='Title of news', max_length=100)),
                ('Image', models.ImageField(help_text='Image Poster for news ', upload_to='')),
                ('Details', models.TextField(help_text='News details', max_length=30000)),
                ('date', models.DateField(help_text='Date of news')),
            ],
        ),
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('home_project', models.IntegerField(default=0)),
                ('project_grant', models.IntegerField(default=0)),
                ('education_child', models.IntegerField(default=0)),
                ('family_aid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image Poster for news ', upload_to='')),
                ('details', models.CharField(help_text='News details', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_volunteers', models.CharField(help_text='type or field of voulnteer', max_length=100)),
                ('RegisterDate', models.DateField(help_text='Date of registration')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('mailing_address', models.CharField(blank=True, max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
