# Generated by Django 4.2 on 2023-05-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zahrweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumberOfAchivment',
            new_name='Achivment',
        ),
    ]
