# Generated by Django 4.2 on 2023-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahrweb', '0002_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(help_text='Image Poster for news ', upload_to='static/'),
        ),
    ]
