# Generated by Django 4.2 on 2023-06-03 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zahrweb', '0003_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_student',
            new_name='is_naf',
        ),
        migrations.AddField(
            model_name='customuser',
            name='FamilyNumbers',
            field=models.IntegerField(default=0, help_text='number of family numbers '),
        ),
        migrations.AddField(
            model_name='customuser',
            name='NationalNumber',
            field=models.CharField(blank=True, help_text='Enter a user National Number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='RegisterDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(default=1, max_length=50, verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Phone number must contain 10 digits', regex='^\\d{10}$')]),
        ),
    ]
